version: '3.5'

# For this configuration to work properly, you must have a license file mounted into the dotcms service.
# Without a license file, the external ES service will NOT be recognized and utilized.  All documents will
# indexed on the dotcms node directly and will not be persisted between restarts.

networks:
  http_net:
  db_net:
  es_net:
  hz_net:

volumes:
  cms-shared:
  #cms-local:
  dbdata:
  esdata:

services:
  http:
    image: dotcms/haproxy:1.8-os
    environment:
      "HAPROXY_CERT_PATH": '/certs/'
#      "HAPROXY_REDIRECT_HTTPS_ALL": 'true'
#      "HAPROXY_MAINTENANCE_PAGE": '/srv/config/503.http'

    ports:
      - "80:8080"
      - "443:8443"
#    volumes:
#      - /data/dotcms/haproxy/certs:/certs:ro
#      - /data/dotcms/haproxy/503.http:/srv/config/503.http:ro

    networks:
      - http_net

  hazelcast:
    image: dotcms/hazelcast:3.9.2-os
    environment:
      "PROVIDER_HAZELCAST_DNSNAMES": 'hazelcast'
      "PROVIDER_HAZELCAST_HEAP_MIN": '128m'
      "PROVIDER_HAZELCAST_HEAP_MAX": '512m'
      "PROVIDER_HAZELCAST_MANCENTER_ENABLED": 'true'
      "PROVIDER_HAZELCAST_MANCENTER_URL": 'http://hazelcast-mancenter:8080/mancenter'
    networks:
      - hz_net

  #hazelcast-mancenter is a totally optional service that provides insights into 
  # the hazelcast cache.  It will function for a cluster of up to two hazelcast
  # nodes.  If you wish to use it with clusters with more than two nodes, you 
  # will need to purchase a license from Hazelcast.
  # https://docs.hazelcast.org/docs/latest-development/manual/html/License_Questions.html
  hazelcast-mancenter:
    image: dotcms/hazelcast-mancenter:3.9.2-os
    ports:
      - "8080:8080"
    networks:
      - hz_net

  elasticsearch:
    image: gcr.io/cicd-246518/es-open-distro:1.2.0
    ports:
      - "9200:9200"
    environment:
      "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1500m'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch,elasticsearch-slave'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP": '1'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '2'
      "ES_ADMIN_PASSWORD": 'admin'
      node.name: elasticsearch
      node.master: 'true'
      discovery.seed_hosts: elasticsearch
      cluster.initial_master_nodes: elasticsearch
    volumes:
      - esdata:/data
    networks:
      - es_net

  elasticsearch-slave:
    image: gcr.io/cicd-246518/es-open-distro:1.2.0
    depends_on:
      - elasticsearch
    environment:
      "PROVIDER_ELASTICSEARCH_HEAP_SIZE": '1024m'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch,elasticsearch-slave'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN": '3'
      "PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX": '30'
      "ES_ADMIN_PASSWORD": 'admin'
      node.name: elasticsearch-slave
      node.master: 'false'
      discovery.seed_hosts: elasticsearch
      cluster.initial_master_nodes: elasticsearch
    networks:
      - es_net

  dotcms:
    image: dotcms/master:latest
    environment:
      "CMS_HEAP_SIZE": '2g'
      "CMS_JAVA_OPTS": '-XX:+PrintFlagsFinal'
      "PROVIDER_DB_DNSNAME": 'db'
      "PROVIDER_ELASTICSEARCH_DNSNAMES": 'elasticsearch, elasticsearch-slave'
      "PROVIDER_HAZELCAST_DNSNAMES": 'hazelcast'
      "ES_ADMIN_PASSWORD": 'admin'
    depends_on:
      - elasticsearch
      - hazelcast
      - db
      - http
    volumes:
      #- cms-shared:/data/shared
      #- [serverpath]/license.dat:/data/local/dotsecure/license/license.dat
      #- [serverpath]/license.zip:/data/shared/assets/license.zip
      - ${PWD}/license.zip:/data/shared/assets/license.zip
    networks:
      - db_net
      - http_net
      - es_net
      - hz_net

  db:
    image: bitnami/postgresql:9.6
    environment:
      "POSTGRESQL_USERNAME": 'dotcmsdbuser'
      "POSTGRESQL_PASSWORD": 'password'
      "POSTGRESQL_DATABASE": 'dotcms'
    volumes:
      - dbdata:/bitnami/postgresql
    networks:
      - db_net
